dbt_example:
  target: dev
  outputs:
    dev:
      dataset: "{{ env_var('DBT_DBNAME', 'dbt_dw') }}"
      method: service-account
      project: 'personalproject-509914'
      threads: 4
      type: bigquery
      keyfile: '/home/thiago/.dbt/personalproject-509914-53ea18c9006f.json'
