dbt_example:
  target: dev
  outputs:
    dev:
      dataset: "{{ env_var('DBT_DBNAME', 'dbt_dw') }}"
      method: service-account
      project: "{{ env_var('PROJECT_NAME', '') }}"
      threads: 4
      type: bigquery
      keyfile: "{{ env_var('FILE_PATH', '') }}"
